version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini
      - ./shared:/shared

  client1:
    container_name: client1
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=INFO
      - BETS_FILE=agency-1.csv
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.ini:/config.ini
      - ./shared:/shared
      - ./.data/dataset:/data

  client2:
    container_name: client2
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=2
      - CLI_LOG_LEVEL=INFO
      - BETS_FILE=agency-2.csv
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.ini:/config.ini
      - ./shared:/shared
      - ./.data/dataset:/data
  
  client3:
    container_name: client3
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=3
      - CLI_LOG_LEVEL=INFO
      - BETS_FILE=agency-3.csv
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.ini:/config.ini
      - ./shared:/shared
      - ./.data/dataset:/data

  client4:
    container_name: client4
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=4
      - CLI_LOG_LEVEL=INFO
      - BETS_FILE=agency-4.csv
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.ini:/config.ini
      - ./shared:/shared
      - ./.data/dataset:/data

  client5:
    container_name: client5
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=5
      - CLI_LOG_LEVEL=INFO
      - BETS_FILE=agency-5.csv
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.ini:/config.ini
      - ./shared:/shared
      - ./.data/dataset:/data

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24